version: '3.8'

x-logging-options: &default-logging
  driver: json-file
  options:
    max-size: '10m'
    max-file: '5'

services:
  ahv-ai-core:
    build: .
    image: ${CI_REGISTRY_IMAGE:-ahv-ai-core}:${TAG:-latest}
    container_name: ahv-ai-core
    
    volumes:
      - /etc/nginx/conf.d:/app/nginx-config
      
    security_opt:
      - no-new-privileges:true
      
    ports:
      - '${PORT:-5006}:${PORT:-5006}'
      
    env_file: .env
    
    healthcheck:
      test: ['CMD-SHELL', 'curl --fail http://localhost:${PORT:-5006}/api/v1/health || exit 1']
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s
      
    restart: unless-stopped
    
    logging: *default-logging
    
    networks:
      - shared_network

networks:
  shared_network:
    external: true
    name: ${CUSTOMER:-dev}_internal_net
