/** @type {import('ts-jest').JestConfigWithTsJest} */
module.exports = {
  preset: 'ts-jest',
  testEnvironment: 'node',
  roots: ['<rootDir>/src'],
  testMatch: ['**/*.test.ts'],
  setupFiles: ['<rootDir>/src/test/setup.ts'],
  transform: {
    '^.+\\.tsx?$': ['ts-jest', {
      tsconfig: 'tsconfig.test.json',
      diagnostics: {
        ignoreCodes: [5107],
      },
    }],
  },
  moduleNameMapper: {
    '^@/(.*)$': '<rootDir>/src/$1',
  },
  collectCoverage: true,
  coverageDirectory: 'coverage',
  coverageReporters: ['text', 'lcov', 'clover', 'html'],
  collectCoverageFrom: [
    'src/**/*.ts',
    '!src/**/*.interface.ts',
    '!src/**/*.model.ts',
    '!src/**/*.swagger.ts',
    '!src/**/*.validation.ts',
    '!src/**/*.route.ts',
    '!src/**/*.controller.ts',
    '!src/server.ts',
    '!src/app.ts',
    '!src/common/config/**',
    '!src/common/configs/**',
    '!src/common/constants/**',
    '!src/common/interfaces/**',
    '!src/common/middlewares/**',
    '!src/common/utils/logger.ts',
    '!src/routes/**',
    '!src/types/**',
  ],
  verbose: true,
  forceExit: true,
  clearMocks: true,
  resetMocks: true,
  restoreMocks: true,
};
